esphome:
  name: ${name}
  friendly_name: ${friendlyName}
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: false

uart:
  id: uart_ecodan
  rx_pin:
    number: GPIO26
    mode:
      input: true
      pullup: true
  tx_pin:
    number: GPIO32
    mode:
      output: true
  baud_rate: 2400
  parity: EVEN
  stop_bits: 1
  # debug:
  #   direction: BOTH
  #   dummy_receiver: false
  #   after:
  #     delimiter: "\n"
  #   sequence:
  #     - lambda: UARTDebug::log_hex(direction, bytes, ' ');

###  ESP restart button
button:
  - platform: restart
    id: restart_button
    name: ${restart_button}

sensor:
  - platform: internal_temperature
    name: ${internal_esp_temperature}
    entity_category: diagnostic